# Generated by Django 5.1.5 on 2026-08-10 03:23

import apps.accounts.managers
import apps.accounts.models
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='F.I.SH.')),
                ('role', models.CharField(choices=[('client', 'Mijoz'), ('barber', 'Usta'), ('superadmin', 'Super admin')], db_index=True, default='client', max_length=16, verbose_name='rol')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.avatar_upload_to, verbose_name='avatar')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='telefon tasdiqlangan')),
                ('google_sub', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Google sub')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('is_staff', models.BooleanField(default=False, verbose_name='xodim')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name="ro'yxatdan o'tgan")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'foydalanuvchi',
                'verbose_name_plural': 'foydalanuvchilar',
                'db_table': 'profiles',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('code_hash', models.CharField(max_length=64)),
                ('purpose', models.CharField(choices=[('login', 'Kirish'), ('phone_change', 'Raqam almashtirish')], default='login', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'SMS kod',
                'verbose_name_plural': 'SMS kodlar',
                'db_table': 'phone_otps',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['phone', 'is_used', '-created_at'], name='phone_otps_phone_eb115b_idx')],
            },
        ),
    ]
