# Generated by Django 5.1.5 on 2026-08-10 03:23

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='nomi')),
                ('description', models.TextField(blank=True, verbose_name='tavsif')),
                ('specialty', models.CharField(choices=[('men', 'Erkaklar'), ('women', 'Ayollar'), ('kids', 'Bolalar'), ('unisex', 'Aralash')], db_index=True, default='unisex', max_length=16, verbose_name="yo'nalish")),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='manzil')),
                ('district', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='tuman')),
                ('city', models.CharField(db_index=True, default='Toshkent', max_length=100, verbose_name='shahar')),
                ('location_lat', models.FloatField(db_index=True, verbose_name='kenglik (lat)')),
                ('location_lng', models.FloatField(db_index=True, verbose_name='uzunlik (lng)')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefon')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='salons/', verbose_name='muqova rasmi')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='faol')),
                ('rating_avg', models.FloatField(default=0, verbose_name="o'rtacha reyting")),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='sharhlar soni')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_salons', to=settings.AUTH_USER_MODEL, verbose_name='egasi')),
            ],
            options={
                'verbose_name': 'salon',
                'verbose_name_plural': 'salonlar',
                'db_table': 'salons',
                'ordering': ('-rating_avg', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('specialty', models.CharField(choices=[('men', 'Erkaklar'), ('women', 'Ayollar'), ('kids', 'Bolalar'), ('unisex', 'Aralash')], db_index=True, default='men', max_length=16, verbose_name='mutaxassislik')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('blocked', 'Bloklangan')], db_index=True, default='active', max_length=16, verbose_name='holat')),
                ('bio', models.TextField(blank=True, verbose_name="o'zi haqida")),
                ('experience_years', models.PositiveSmallIntegerField(default=0, verbose_name='tajriba (yil)')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='barbers/', verbose_name='rasm')),
                ('location_lat', models.FloatField(blank=True, db_index=True, null=True, verbose_name='kenglik (lat)')),
                ('location_lng', models.FloatField(blank=True, db_index=True, null=True, verbose_name='uzunlik (lng)')),
                ('services', models.JSONField(blank=True, default=list, verbose_name='xizmatlar')),
                ('default_slot_minutes', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(240)], verbose_name='standart slot (daqiqa)')),
                ('rating_avg', models.FloatField(default=0, verbose_name="o'rtacha reyting")),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='sharhlar soni')),
                ('completed_bookings', models.PositiveIntegerField(default=0, verbose_name='bajarilgan navbatlar')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barber', to=settings.AUTH_USER_MODEL, verbose_name='profil')),
                ('salon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barbers', to='salons.salon', verbose_name='salon')),
            ],
            options={
                'verbose_name': 'usta',
                'verbose_name_plural': 'ustalar',
                'db_table': 'barbers',
                'ordering': ('-rating_avg', '-completed_bookings'),
            },
        ),
        migrations.CreateModel(
            name='BarberDayOff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('date', models.DateField(db_index=True, verbose_name='sana')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='sabab')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_off', to='salons.barber')),
            ],
            options={
                'verbose_name': 'dam olish kuni',
                'verbose_name_plural': 'dam olish kunlari',
                'db_table': 'barber_days_off',
                'ordering': ('-date',),
                'constraints': [models.UniqueConstraint(fields=('barber', 'date'), name='uniq_barber_dayoff')],
            },
        ),
        migrations.CreateModel(
            name='BarberSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Dushanba'), (1, 'Seshanba'), (2, 'Chorshanba'), (3, 'Payshanba'), (4, 'Juma'), (5, 'Shanba'), (6, 'Yakshanba')], verbose_name='hafta kuni')),
                ('is_working', models.BooleanField(default=True, verbose_name='ishlaydi')),
                ('start_time', models.TimeField(default=datetime.time(9, 0), verbose_name='ish boshlanishi')),
                ('end_time', models.TimeField(default=datetime.time(20, 0), verbose_name='ish tugashi')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='tanaffus boshi')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='tanaffus oxiri')),
                ('slot_minutes', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(240)], verbose_name='slot uzunligi (daqiqa)')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='salons.barber')),
            ],
            options={
                'verbose_name': 'ish jadvali',
                'verbose_name_plural': 'ish jadvallari',
                'db_table': 'barber_schedules',
                'ordering': ('barber', 'weekday'),
                'constraints': [models.UniqueConstraint(fields=('barber', 'weekday'), name='uniq_barber_weekday'), models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='schedule_end_after_start')],
            },
        ),
        migrations.AddIndex(
            model_name='salon',
            index=models.Index(fields=['location_lat', 'location_lng'], name='salons_locatio_c0b552_idx'),
        ),
        migrations.AddIndex(
            model_name='barber',
            index=models.Index(fields=['status', 'specialty'], name='barbers_status_335209_idx'),
        ),
    ]
