# Generated by Django 5.1.5 on 2026-08-10 03:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('booking_date', models.DateField(db_index=True, verbose_name='sana')),
                ('booking_time', models.TimeField(verbose_name='vaqt')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=30, verbose_name='davomiyligi (daqiqa)')),
                ('service_name', models.CharField(max_length=100, verbose_name='xizmat')),
                ('price', models.PositiveIntegerField(default=0, verbose_name="narx (so'm)")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlangan'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], db_index=True, default='pending', max_length=16, verbose_name='holat')),
                ('client_note', models.CharField(blank=True, max_length=500, verbose_name='mijoz izohi')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255, verbose_name='bekor qilish sababi')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='salons.barber', verbose_name='usta')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='mijoz')),
                ('salon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='salons.salon', verbose_name='salon')),
            ],
            options={
                'verbose_name': 'navbat',
                'verbose_name_plural': 'navbatlar',
                'db_table': 'bookings',
                'ordering': ('-booking_date', '-booking_time'),
                'indexes': [models.Index(fields=['barber', 'booking_date', 'status'], name='bookings_barber__325e61_idx'), models.Index(fields=['client', '-booking_date'], name='bookings_client__2ced44_idx'), models.Index(fields=['status', 'booking_date'], name='bookings_status_b2c90c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('barber', 'booking_date', 'booking_time'), name='uniq_active_booking_slot')],
            },
        ),
    ]
