# Generated by Django 5.1.5 on 2026-08-10 03:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('salons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('rating', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='baho')),
                ('comment', models.TextField(blank=True, max_length=1000, verbose_name='izoh')),
                ('barber_reply', models.TextField(blank=True, max_length=1000, verbose_name='usta javobi')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='salons.barber', verbose_name='usta')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking', verbose_name='navbat')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='mijoz')),
                ('salon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='salons.salon', verbose_name='salon')),
            ],
            options={
                'verbose_name': 'sharh',
                'verbose_name_plural': 'sharhlar',
                'db_table': 'reviews',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['barber', '-created_at'], name='reviews_barber__761f64_idx')],
            },
        ),
    ]
