# Generated by Django 5.1.5 on 2026-08-23 13:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_booking_reminder_sent_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='sarlavha')),
                ('body', models.TextField(max_length=1000, verbose_name='matn')),
                ('kind', models.CharField(choices=[('booking_confirmed', 'Navbat tasdiqlandi'), ('booking_cancelled', 'Navbat bekor qilindi'), ('booking_completed', 'Navbat yakunlandi'), ('booking_reminder', 'Navbat eslatmasi'), ('booking_created', 'Yangi navbat'), ('system', 'Tizim xabari')], default='system', max_length=32, verbose_name='turi')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='havola')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name="o'qilgan")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='yaratilgan')),
                ('push_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='push yuborilgan')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='bookings.booking', verbose_name='navbat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
            ],
            options={
                'verbose_name': 'xabarnoma',
                'verbose_name_plural': 'xabarnomalar',
                'db_table': 'notifications',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_611c58_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx')],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.TextField(unique=True, verbose_name='endpoint')),
                ('auth_keys', models.JSONField(verbose_name='kalitlar')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='qurilma')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="qo'shilgan")),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='oxirgi muvaffaqiyatli yuborish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
            ],
            options={
                'verbose_name': 'push obuna',
                'verbose_name_plural': 'push obunalar',
                'db_table': 'push_subscriptions',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='push_subscr_user_id_e50086_idx')],
            },
        ),
    ]
